plugins {
    id 'fabric-loom' version '1.9-SNAPSHOT'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_name
}

repositories {
    maven {
        name = 'GeckoLib'
        url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
        content {
            includeGroupByRegex("software\\.bernie.*")
            includeGroup("com.eliotlash.mclib")
        }
    }
    maven { url "https://maven.shedaniel.me/" }
    maven { url "https://cursemaven.com" }
    maven {
        name = 'Terraformers'
        url = 'https://maven.terraformersmc.com/'
    }
    maven {
        url = "https://api.modrinth.com/maven"
    }
}

loom {
}

dependencies {
    minecraft "net.minecraft:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()

    modImplementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    modImplementation "software.bernie.geckolib:geckolib-fabric-${project.minecraft_version}:${project.geckolib_version}"
    modImplementation include("maven.modrinth:midnightlib:${project.midnightlib_fabric_version}-fabric")
    modImplementation "com.terraformersmc:modmenu:${project.mod_menu_version}"

    modApi include("me.shedaniel.cloth:cloth-config-fabric:${project.cloth_fabric_version}") {
        exclude(group: "net.fabricmc.fabric-api")
    }
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}" }
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_name
            from components.java
        }
    }

    repositories {
    }
}
