org.gradle.jvmargs=-Xmx4G
org.gradle.workers.max=5
org.gradle.parallel=true

mod.id=naturalist
mod.name=Naturalist
mod.group=com.starfish_studios
mod.version=6.0pre1
mod.description=Enhances the overworld by adding new wildlife with unique behavior!

deps.fabric-loader=0.16.9

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.forge=[VERSIONED]
deps.parchment=[VERSIONED]
deps.geckolib=[VERSIONED]
deps.cloth_config=[VERSIONED]
deps.modmenu=[VERSIONED]
deps.midnightlib=[VERSIONED]

mod.mc_dep_fabric=[VERSIONED]
mod.mc_dep_forgelike=[VERSIONED]

publish.modrinth=
publish.curseforge=
#publish.additionalVersions=
