architectury {
    common rootProject.enabled_platforms.split(',')
}

repositories {
    maven {
        name = 'GeckoLib'
        url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
        content {
            includeGroupByRegex("software\\.bernie.*")
            includeGroup("com.eliotlash.mclib")
        }
    }
    maven { url "https://maven.shedaniel.me/" }
    maven { url "https://cursemaven.com" }
    maven {
        name = 'Terraformers'
        url = 'https://maven.terraformersmc.com/'
    }
}

dependencies {
    minecraft "net.minecraft:minecraft:$rootProject.minecraft_version"
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    modImplementation ("software.bernie.geckolib:geckolib-fabric-1.21.4:${rootProject.geckolib_version}")
    mappings loom.layered {
        it.officialMojangMappings()
        it.parchment("org.parchmentmc.data:parchment-1.21.4:${rootProject.parchment_version}")
    }
}